import 'package:flutter/material.dart';
// import 'package:quiz_app/screens/home_page.dart';
import 'quizselection_page.dart';

// void main() {
//   runApp(const FigmaToCodeApp());
// }

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
// class FigmaToCodeApp extends StatelessWidget {
//   const FigmaToCodeApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       theme: ThemeData.dark().copyWith(
//         scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
//       ),
//       home: Scaffold(
//         body: ListView(children: [
//           Home(),
//         ]),
//       ),
//     );
//   }
// }

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 1079,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFFF4F4F4)),
          child: Stack(
            children: [
              Positioned(
                left: 13,
                top: 938,
                child: Container(
                  width: 350,
                  height: 95,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, 0.09),
                      end: Alignment(0.02, 0.96),
                      colors: [
                        const Color(0xFF6345F1) /* Base-Color */,
                        const Color(0xFF39278B)
                      ],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 951,
                child: SizedBox(
                  width: 146,
                  height: 19,
                  child: Text(
                    'Pemrograman  Website',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.83,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 1000,
                child: SizedBox(
                  width: 79,
                  height: 17,
                  child: Text(
                    '20 Questions',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.83,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 975,
                child: SizedBox(
                  width: 55,
                  height: 20,
                  child: Text(
                    'HTML',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 1.38,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 243,
                top: 969,
                child: Container(
                  width: 100,
                  height: 33,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF6345F1) /* Base-Color */,
                      ),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 256.68,
                top: 974.66,
                child: SizedBox(
                  width: 73.50,
                  height: 22.63,
                  child: Text(
                    'Take Quiz!',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF6345F1) /* Base-Color */,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 222,
                child: Container(
                  width: 349,
                  height: 105,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 2,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 240,
                child: Text(
                  'Daily Challenge',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF6345F1) /* Base-Color */,
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 180,
                child: SizedBox(
                  width: 311,
                  height: 15,
                  child: Text(
                    'Ready to learn something new today?',
                    style: TextStyle(
                      color: const Color(0xFF826BEF) /* Second-Color */,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 1,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 134,
                child: Text(
                  'Hello, Jonathan!',
                  style: TextStyle(
                    color: const Color(0xFF6345F1) /* Base-Color */,
                    fontSize: 24,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 311,
                top: 353,
                child: SizedBox(
                  width: 58,
                  height: 15,
                  child: Text(
                    'See All',
                    style: TextStyle(
                      color: const Color(0xFF826BEF) /* Second-Color */,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 1,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 342,
                child: Text(
                  'Categories',
                  style: TextStyle(
                    color: const Color(0xFF6345F1) /* Base-Color */,
                    fontSize: 24,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 388,
                child: Container(
                  width: 350,
                  height: 95,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, 0.09),
                      end: Alignment(0.02, 0.96),
                      colors: [
                        const Color(0xFF6345F1) /* Base-Color */,
                        const Color(0xFF39278B)
                      ],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 401,
                child: SizedBox(
                  width: 146,
                  height: 19,
                  child: Text(
                    'Pemrograman  Website',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.83,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 450,
                child: SizedBox(
                  width: 79,
                  height: 17,
                  child: Text(
                    '20 Questions',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.83,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 425,
                child: SizedBox(
                  width: 55,
                  height: 20,
                  child: Text(
                    'HTML',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 1.38,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 250,
                top: 419,
                child: Container(
                  width: 100,
                  height: 33,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF6345F1) /* Base-Color */,
                      ),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 263.68,
                top: 424.66,
                child: SizedBox(
                  width: 73.50,
                  height: 22.63,
                  child: Text(
                    'Take Quiz!',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF6345F1) /* Base-Color */,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 498,
                child: Container(
                  width: 350,
                  height: 95,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, 0.09),
                      end: Alignment(0.02, 0.96),
                      colors: [
                        const Color(0xFF6345F1) /* Base-Color */,
                        const Color(0xFF39278B)
                      ],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 511,
                child: SizedBox(
                  width: 146,
                  height: 19,
                  child: Text(
                    'Pemrograman  Website',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.83,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 560,
                child: SizedBox(
                  width: 79,
                  height: 17,
                  child: Text(
                    '20 Questions',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.83,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 535,
                child: SizedBox(
                  width: 55,
                  height: 20,
                  child: Text(
                    'HTML',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 1.38,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 251,
                top: 529,
                child: Container(
                  width: 100,
                  height: 33,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF6345F1) /* Base-Color */,
                      ),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 264.68,
                top: 534.66,
                child: SizedBox(
                  width: 73.50,
                  height: 22.63,
                  child: Text(
                    'Take Quiz!',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF6345F1) /* Base-Color */,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 608,
                child: Container(
                  width: 350,
                  height: 95,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, 0.09),
                      end: Alignment(0.02, 0.96),
                      colors: [
                        const Color(0xFF6345F1) /* Base-Color */,
                        const Color(0xFF39278B)
                      ],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 621,
                child: SizedBox(
                  width: 146,
                  height: 19,
                  child: Text(
                    'Pemrograman  Website',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.83,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 670,
                child: SizedBox(
                  width: 79,
                  height: 17,
                  child: Text(
                    '20 Questions',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.83,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 645,
                child: SizedBox(
                  width: 55,
                  height: 20,
                  child: Text(
                    'HTML',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 1.38,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 249,
                top: 639,
                child: Container(
                  width: 100,
                  height: 33,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF6345F1) /* Base-Color */,
                      ),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 262.68,
                top: 644.66,
                child: SizedBox(
                  width: 73.50,
                  height: 22.63,
                  child: Text(
                    'Take Quiz!',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF6345F1) /* Base-Color */,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 718,
                child: Container(
                  width: 350,
                  height: 95,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, 0.09),
                      end: Alignment(0.02, 0.96),
                      colors: [
                        const Color(0xFF6345F1) /* Base-Color */,
                        const Color(0xFF39278B)
                      ],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 731,
                child: SizedBox(
                  width: 146,
                  height: 19,
                  child: Text(
                    'Pemrograman  Website',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.83,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 780,
                child: SizedBox(
                  width: 79,
                  height: 17,
                  child: Text(
                    '20 Questions',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.83,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 755,
                child: SizedBox(
                  width: 55,
                  height: 20,
                  child: Text(
                    'HTML',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 1.38,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 247,
                top: 749,
                child: Container(
                  width: 100,
                  height: 33,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF6345F1) /* Base-Color */,
                      ),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 260.68,
                top: 754.66,
                child: SizedBox(
                  width: 73.50,
                  height: 22.63,
                  child: Text(
                    'Take Quiz!',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF6345F1) /* Base-Color */,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 828,
                child: Container(
                  width: 350,
                  height: 95,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(1.00, 0.09),
                      end: Alignment(0.02, 0.96),
                      colors: [
                        const Color(0xFF6345F1) /* Base-Color */,
                        const Color(0xFF39278B)
                      ],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 35,
                top: 841,
                child: SizedBox(
                  width: 146,
                  height: 19,
                  child: Text(
                    'Pemrograman  Website',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.83,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 35,
                top: 890,
                child: SizedBox(
                  width: 79,
                  height: 17,
                  child: Text(
                    '20 Questions',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.83,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 35,
                top: 865,
                child: SizedBox(
                  width: 55,
                  height: 20,
                  child: Text(
                    'HTML',
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 1.38,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 245,
                top: 859,
                child: Container(
                  width: 100,
                  height: 33,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF6345F1) /* Base-Color */,
                      ),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 258.68,
                top: 864.66,
                child: SizedBox(
                  width: 73.50,
                  height: 22.63,
                  child: Text(
                    'Take Quiz!',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF6345F1) /* Base-Color */,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 282,
                child: Text(
                  'Take 10 Quiz',
                  style: TextStyle(
                    color: const Color(0xFF6345F1) /* Base-Color */,
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 280,
                top: 285,
                child: Container(
                  width: 70,
                  height: 25,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF6345F1) /* Base-Color */,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 300,
                top: 289,
                child: Text(
                  'Start',
                  style: TextStyle(
                    color: Colors.white /* White-Color */,
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 301,
                top: 245,
                child: Container(
                  width: 28,
                  height: 28,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/28x28"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 997,
                child: Container(
                  width: 393,
                  height: 82,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 393,
                          height: 82,
                          decoration: BoxDecoration(
                            color: const Color(0xFFF9FAFB) /* White-Color */,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 11,
                        child: Container(
                          width: 30,
                          height: 30,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 30,
                        top: 46,
                        child: Text(
                          'Home',
                          style: TextStyle(
                            color:
                                const Color(0xFF2563EB) /* Base-Blue-Color */,
                            fontSize: 12,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 126,
                        top: 11,
                        child: Container(
                          width: 30,
                          height: 30,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 121,
                        top: 46,
                        child: Text(
                          'Explore',
                          style: TextStyle(
                            color:
                                const Color(0xFF909090) /* Grey-Base-Color */,
                            fontSize: 12,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 228,
                        top: 11,
                        child: Container(
                          width: 30,
                          height: 30,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 220,
                        top: 46,
                        child: Text(
                          'Courses',
                          style: TextStyle(
                            color:
                                const Color(0xFF909090) /* Grey-Base-Color */,
                            fontSize: 12,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 9,
                        child: Container(
                          width: 30,
                          height: 30,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 325,
                        top: 44,
                        child: Text(
                          'Profile',
                          style: TextStyle(
                            color:
                                const Color(0xFF909090) /* Grey-Base-Color */,
                            fontSize: 12,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 110,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 62,
                child: Text(
                  'MIQUIZ',
                  style: TextStyle(
                    color: const Color(0xFF6345F1) /* Base-Color */,
                    fontSize: 24,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 335,
                top: 62,
                child: Container(
                  width: 35,
                  height: 35,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/35x35"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(360),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 303,
                top: 69,
                child: Container(
                  width: 20,
                  height: 22,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/20x22"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 301,
                top: 16,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 4,
                  children: [
                    Container(width: 20, height: 14, child: Stack()),
                    Container(width: 16, height: 14, child: Stack()),
                    Container(
                      width: 25,
                      height: 14,
                      child: Stack(
                        children: [
                          Positioned(
                            left: 2,
                            top: 3,
                            child: Container(
                              width: 19,
                              height: 8,
                              decoration: ShapeDecoration(
                                color: Colors.black,
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(1)),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 30,
                top: 16,
                child: Container(width: 33, height: 15, child: Stack()),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
