import 'package:flutter/material.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
// class FigmaToCodeApp extends StatelessWidget {
//   const FigmaToCodeApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       theme: ThemeData.dark().copyWith(
//         scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
//       ),
//       home: Scaffold(
//         body: ListView(children: [
//           PemrogramanMobile(),
//         ]),
//       ),
//     );
//   }
// }

class PemrogramanMobile extends StatelessWidget {
  const PemrogramanMobile({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            color: const Color(0xFF6345F1) /* Base-Color */,
          ),
          child: Stack(
            children: [
              Positioned(
                left: 32,
                top: 324,
                child: Container(
                  width: 330,
                  height: 67.07,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x66000000),
                        blurRadius: 10,
                        offset: Offset(0, 5),
                        spreadRadius: 5,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 101,
                top: 347.47,
                child: SizedBox(
                  width: 193,
                  height: 20.12,
                  child: Text(
                    'HTML, CSS, JAVASCRIPT',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF6345F1) /* Base-Color */,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 411.07,
                child: Container(
                  width: 330,
                  height: 67.07,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x66000000),
                        blurRadius: 10,
                        offset: Offset(0, 5),
                        spreadRadius: 5,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 101,
                top: 434.54,
                child: SizedBox(
                  width: 193,
                  height: 20.12,
                  child: Text(
                    'HTML, CSS, JAVASCRIPT',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF6345F1) /* Base-Color */,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 498.14,
                child: Container(
                  width: 330,
                  height: 67.07,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x66000000),
                        blurRadius: 10,
                        offset: Offset(0, 5),
                        spreadRadius: 5,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 101,
                top: 521.61,
                child: SizedBox(
                  width: 193,
                  height: 20.12,
                  child: Text(
                    'HTML, CSS, JAVASCRIPT',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF6345F1) /* Base-Color */,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 585.21,
                child: Container(
                  width: 330,
                  height: 67.07,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x66000000),
                        blurRadius: 10,
                        offset: Offset(0, 5),
                        spreadRadius: 5,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 101,
                top: 608.68,
                child: SizedBox(
                  width: 193,
                  height: 20.12,
                  child: Text(
                    'HTML, CSS, JAVASCRIPT',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF6345F1) /* Base-Color */,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 174,
                child: SizedBox(
                  width: 317,
                  child: Text(
                    'Bahasa Pemrograman yang digunakan dalam pemrograman wesite adalah',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white /* White-Color */,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 77,
                top: 80,
                child: Text(
                  'Pemrograman Website',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 138.02,
                child: Container(
                  transform: Matrix4.identity()
                    ..translate(0.0, 0.0)
                    ..rotateZ(-1.57),
                  width: 58.02,
                  height: 30,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
